### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by kouvel** [Microsoft/xunit-performance#266]
Just some random thoughts. I'm not too familiar with xunit-performance, so I'm not sure if any of these are already provided. If there's interest in any of the items feel free to split them up into separate issues.

1. Provide a way for a test to run for a fixed amount of time rather than for a fixed number of iterations
- This could report iterations of InnerIteration groups per unit of time instead of time per InnerIteration group
- This scales better across processors and platforms and InnerIteration count tweaking would be unnecessary (some small and reasonable value should suffice)
- It should be easy to modify the test to run a fixed number of iterations when profiling is necessary
- Allow the test to specify warmup and measured durations
- May look something like:

```
[Benchmark(WarmupDurationMs = 10, TestDurationMs = 100, ReportUnits = ReportingUnits.IterationsPerMillisecond)]
public static void AllocateTest()
{
    object obj = null;
    for(int i = 0; i < 1000; ++i)
        obj = new object();
}
```

2. Provide another option to just have the test do the measurement and report a result as a time or score, for some extra flexibility including nontrivial setup/teardown and custom warmup/test. Utilities for taking measurements and doing calculations may be provided in libraries. May look like:

```
[Benchmark(CustomReport = Score, ReportUnits = ReportingUnits.IterationsPerMillisecond)]
public static int MultithreadedAllocateTest(BenchmarkHelper helper)
{
    // setup phase
    var allocationCounts = new int[threadCount]; // or something better for tallying counts
    // create and start a bunch of threads that allocate new object() in a loop and tally counts 1000 allocations at a time into allocationCounts

    // warmup phase
    Thread.Sleep(10);
    // zero allocationCounts

    // measured test phase, here it's just a sleep but another option instead of helper.Run() may be helper.RunForMilliseconds(100, ...) if using a loop with inner iterations
    helper.Run(() =>
    {
        Thread.Sleep(100);
    });
    int iterations = allocationCounts.Sum();

    // teardown phase
    // stop threads

    return helper.GetIterationsPerMillisecond(iterations);
}
```

3. Not sure if there is a way to disable ETW event collection. Would be nice to disable it by default to remove a variable, they can be collected when needed. The runner should be able to control the default (CI may want to collect data for later investigation).

4. Provide error in % (maybe standard error) so that it's easy to tell from a glance which tests were noisy

5. Provide ability to run multiple iterations of the test
- Or even better would be to provide a way to specify minimum and maximum number of iterations over the whole test, a target standard error %, and have the harness run iterations until the error is below the target

6. I assume a GC.Collect is done between test invocations, I think at least GC.Collect + GC.WaitForPendingFinalizers + GC.WaitForPendingFinalizers should be done between tests and between outer test iterations to eliminate GC time from one bleeding into the next.

7. A question rather than a suggestion, what's the advantage of providing InnerIterationCount to the attribute and using that in the test, rather than not providing anything and using a constant? I can see the benefit if the finally reported result reports a number relevant to each inner iteration. That may be useful but using InnerIterationCount in the for-loop also seems to add some noticeable overhead in microbenchmarks. Could manually load it outside the loop and I assume that would fix it, but wondering if it would just be simpler to eliminate InnerIterationCount?

**Comment by kouvel** [comment]
CC @adamsitnik

**Comment by adamsitnik** [comment]
@kouvel how to get this with BenchmarkDotNet:

In BDN we have a thing called Jobs and they allow you to configure benchmarks. You can do it by using attributes or our fluent API or our object initialization API.

> 1 Provide a way for a test to run for a fixed amount of time rather than for a fixed number of iterations

You can specify the number of iterations and invocation per iteration or use our heuristics to get stable results without providing any values (default mode). You can also specify the minimum iteration time which will be respected by our heuristics.

```cs
DefaultConfig.Instance
            .With(
                Job.Default.WithMinIterationTime(TimeInterval.FromSeconds())
```

> 2 Provide another option to just have the test do the measurement and report a result as a time or score, 

What do you mean by score? If you mark one of the Benchmarks/Jobs as the baseline then all other benchmarks are going to be scaled:

```cs
[Benchmark(Baseline = true)]
public void Baseline() => Thread.Sleep(BaseTime);

[Benchmark]
public void Slow() => Thread.Sleep(BaseTime * 2);

[Benchmark]
public void Fast() => Thread.Sleep(BaseTime / 2);
```

You can set the time units in following way:

```cs
var config = ManualConfig.Create(config: DefaultConfig.Instance);
config.Set(new Reports.SummaryStyle
{
	PrintUnitsInHeader = true,
	PrintUnitsInContent = false,
	TimeUnit = TimeUnit.Microsecond,
	SizeUnit = Columns.SizeUnit.B
});
```

> 2 for some extra flexibility including nontrivial setup/teardown and custom warmup/test. Utilities for taking measurements and doing calculations may be provided in libraries. 

We support global setup/cleanup (Executed once) and Iteration Setup/Cleanup (executed for every itereation), the [docs](http://benchmarkdotnet.org/Advanced/SetupAndCleanup.htm)

```cs
public class SetupAndCleanupExample
{
  private int setupCounter;
  private int cleanupCounter;

  [IterationSetup]
  public void IterationSetup() => Console.WriteLine("// " + "IterationSetup" + " (" + ++setupCounter + ")");

  [IterationCleanup]
  public void IterationCleanup() => Console.WriteLine("// " + "IterationCleanup" + " (" + ++cleanupCounter + ")");

  [GlobalSetup]
  public void GlobalSetup() => Console.WriteLine("// " + "GlobalSetup");

  [GlobalCleanup]
  public void GlobalCleanup() => Console.WriteLine("// " + "GlobalCleanup");

  [Benchmark]
  public void Benchmark() => Console.WriteLine("// " + "Benchmark");
}
```

> 3 Not sure if there is a way to disable ETW event collection. 

 We have some ETW diagnosers: Inlining, HardwareCounters and TailCall. They are not enabled by default, moreover, the diagnosers with an overhead run the benchmarks once again, gather the data and ignore the results (they are skewed by the overhead)

Btw I am sure it's possible today with xunit-performance too,

> 4. Provide error in % (maybe standard error) so that it's easy to tell from a glance which tests were noisy

BenchmarkDotNet provides:

- Min, Lower Fence, Q1, Median, Mean, Q3, Upper Fence, Max, Interquartile Range, Outliers
- Standard Error, Variance, Standard Deviation
- Skewness, Kurtosis
- Confidence Interval (Mean, Error, Level, Margin, Lower, Upper)
- Percentiles (P0, P25, P50, P67, P80, P85, P90, P95, P100)

And removes the outliers by default. 

@AndreyAkinshin (the main author of BDN) is a PhD with huge interest in statistics ;)

> 5 Provide ability to run multiple iterations of the test. Or even better would be to provide a way to specify minimum and maximum number of iterations over the whole test, a target standard error %, and have the harness run iterations until the error is below the target

It's our default mode (to run the benchmarks until our herustic is happy about the results), you can configure the accuracy by using some of the Job extension methods:

```cs
 WithMaxRelativeError
 WithMaxAbsoluteError
 WithMinIterationTime
 WithMinInvokeCount
 WithEvaluateOverhead
 WithRemoveOutliers
 WithAnalyzeLaunchVariance
```

> 6 I assume a GC.Collect is done between test invocations, 

BenchmarkDotNet forces `GC.Collect + GC.WaitForPendingFinalizers + GC.Collect` for every iteration. This behavior can be disabled by calling `Job.WithGcForce(false)`

Moreover, by default, we run every benchmark in a new, dedicated process so the self-tuning nature of GC  does not affect the final results and order of executing benchmarks/any other side effects do not matter due to the process isolation.

@kouvel please let me know if you have some more questions!

**Comment by kouvel** [comment]
Sounds very interesting, thanks for the info!

**Comment by kouvel** [comment]
> What do you mean by score?

I meant some opaque value where higher is better. It could just be iterations per unit of time, or sometimes a test may measure several things and produce one value by weighting those measurements. For instance in a test there can be two types of operations happening at the same time (intent is to test both together), but the perf of one may be more important than the other. For testing a reader-writer lock with many readers and few writers, we'd want to see that readers are getting most of the locks but writers are also making progress.

> If you mark one of the Benchmarks/Jobs as the baseline then all other benchmarks are going to be scaled

This could be useful but I was hoping to get some more flexibility with that example. Probably there's already a way though.

**Comment by adamsitnik** [comment]
> I meant some opaque value where higher is better. It could just be iterations per unit of time

We display `Operations/s` by default.
