### ISSUE TITLE
Warn if benchmarking with debugger attached

### ISSUE THREAD

**Issue by jzabroski** [microsoft/xunit-performance#276]
BenchmarkDotNet generates the following warning:

```
// * Warnings *
Environment
  Summary -> Benchmark was executed with attached debugger
```

**Comment by bhushan-firake** [comment]
@jzabroski I don't know if you have figured this out.
If you go to this link: https://benchmarkdotnet.org/articles/guides/good-practices.html#use-the-release-build-without-an-attached-debugger

They have specified running the program from command line after you build it with Optimize code enabled.

You seem to be running from Visual Studio instead of command line.

**Comment by jzabroski** [comment]
This is xunit-performance which is basically a dead project.

**Comment by brianrob** [comment]
Closing prior to archive.
